dataset: 
  comp_dataset: spaceship-titanic
  train_path: "/Users/michellezhou/.cache/kagglehub/competitions/spaceship-titanic/train.csv"
  test_path: "/Users/michellezhou/.cache/kagglehub/competitions/spaceship-titanic/test.csv"

model:
  batch: 128
  iters: 1100
  epochs: 20
  lr: 0.005

train_parameters:
  test_size: 0.2
  state: 23

hydra: 
  job:
    chdir: True
